#!/bin/sh
set -eu

case "${XDG_CURRENT_DESKTOP-}:${XDG_SESSION_TYPE-}" in
    *XFCE*:x11) ;;
    *) echo "Refusing panel changes outside XFCE/X11." >&2; exit 1 ;;
esac

channel=xfce4-panel
panel_ids=
monitor_index=0

set_value() {
    property=$1 type=$2 value=$3
    xfconf-query -c "$channel" -p "$property" -n -t "$type" -s "$value"
}

write_int_array() {
    property=$1
    shift
    arguments=
    for value in "$@"; do
        case "$value" in *[!0-9]*|'') return 2 ;; esac
        arguments="$arguments -t int -s $value"
    done
    # Values are validated integers generated by this script.
    # shellcheck disable=SC2086
    xfconf-query -c "$channel" -p "$property" -n -a $arguments
}

set_panel_geometry() {
    panel_id=$1 output=$2
    geometry=$(xrandr --query | awk -v name="$output" '
        $1 == name && $2 == "connected" {
            for (i = 3; i <= NF; i++)
                if ($i ~ /^[0-9]+x[0-9]+\+[0-9-]+\+[0-9-]+/) {
                    print $i
                    exit
                }
        }')
    width=$(printf '%s\n' "$geometry" | sed -E 's/^([0-9]+)x.*/\1/')
    x_offset=$(printf '%s\n' "$geometry" | sed -E 's/^[0-9]+x[0-9]+\+(-?[0-9]+)\+.*/\1/')
    y_offset=$(printf '%s\n' "$geometry" | sed -E 's/^[0-9]+x[0-9]+\+-?[0-9]+\+(-?[0-9]+).*/\1/')
    center=$((x_offset + width / 2))

    set_value "/panels/panel-$panel_id/position" string \
        "p=6;x=$center;y=$y_offset"
    set_value "/panels/panel-$panel_id/output-name" string "$output"
    set_value "/panels/panel-$panel_id/length" double 100
    set_value "/panels/panel-$panel_id/size" uint 36
    set_value "/panels/panel-$panel_id/icon-size" uint 20
    set_value "/panels/panel-$panel_id/nrows" uint 1
    set_value "/panels/panel-$panel_id/position-locked" bool true
    set_value "/panels/panel-$panel_id/span-monitors" bool false
    set_value "/panels/panel-$panel_id/enable-struts" bool true
    set_value "/panels/panel-$panel_id/background-style" uint 1
    xfconf-query -c "$channel" \
        -p "/panels/panel-$panel_id/background-rgba" -n -a \
        -t double -s 0.043 -t double -s 0.055 \
        -t double -s 0.067 -t double -s 0.98
    set_value "/panels/panel-$panel_id/enter-opacity" uint 100
    set_value "/panels/panel-$panel_id/leave-opacity" uint 100
}

configure_common_plugin() {
    plugin_id=$1 plugin_type=$2
    set_value "/plugins/plugin-$plugin_id" string "$plugin_type"
}

active_outputs_primary_first() {
    xrandr --listactivemonitors | awk '
        NR > 1 {
            if ($2 ~ /\*/)
                primary = primary $NF ORS
            else
                secondary = secondary $NF ORS
        }
        END { printf "%s%s", primary, secondary }
    '
}

# Remove only the reserved portable profile range. Existing configuration was
# backed up by install.sh and can be restored verbatim.
for panel_id in $(seq 81 96); do
    xfconf-query -c "$channel" -p "/panels/panel-$panel_id" -r -R 2>/dev/null || true
done
for plugin_id in $(seq 801 1120); do
    xfconf-query -c "$channel" -p "/plugins/plugin-$plugin_id" -r -R 2>/dev/null || true
done

outputs=$(active_outputs_primary_first)
[ -n "$outputs" ] || {
    echo "No active XRandR monitor was detected." >&2
    exit 1
}

for output in $outputs; do
    panel_id=$((81 + monitor_index))
    base=$((801 + monitor_index * 20))
    whisker=$base
    pager=$((base + 1))
    tasklist=$((base + 2))
    spacer=$((base + 3))
    audio=$((base + 4))
    network=$((base + 5))
    clock=$((base + 6))
    actions=$((base + 7))
    edge=$((base + 8))

    set_panel_geometry "$panel_id" "$output"
    configure_common_plugin "$whisker" whiskermenu
    configure_common_plugin "$pager" pager
    configure_common_plugin "$tasklist" tasklist
    configure_common_plugin "$spacer" separator
    configure_common_plugin "$audio" pulseaudio
    configure_common_plugin "$network" genmon
    configure_common_plugin "$clock" clock
    configure_common_plugin "$actions" actions
    configure_common_plugin "$edge" separator

    set_value "/plugins/plugin-$pager/miniature-view" bool false
    set_value "/plugins/plugin-$pager/rows" uint 1
    set_value "/plugins/plugin-$pager/numbering" bool false
    set_value "/plugins/plugin-$tasklist/include-all-monitors" bool false
    set_value "/plugins/plugin-$tasklist/include-all-workspaces" bool false
    set_value "/plugins/plugin-$tasklist/show-handle" bool false
    set_value "/plugins/plugin-$tasklist/flat-buttons" bool true
    set_value "/plugins/plugin-$tasklist/max-button-length" int 160
    set_value "/plugins/plugin-$tasklist/min-button-length" int 44
    set_value "/plugins/plugin-$spacer/expand" bool true
    set_value "/plugins/plugin-$spacer/style" uint 0
    set_value "/plugins/plugin-$edge/expand" bool false
    set_value "/plugins/plugin-$edge/style" uint 0
    set_value "/plugins/plugin-$audio/enable-keyboard-shortcuts" bool \
        "$([ "$monitor_index" -eq 0 ] && echo true || echo false)"
    set_value "/plugins/plugin-$clock/digital-layout" uint 3
    set_value "/plugins/plugin-$clock/digital-time-format" string '%H:%M'
    set_value "/plugins/plugin-$clock/tooltip-format" string '%A, %d %B %Y'
    set_value "/plugins/plugin-$actions/appearance" uint 1
    set_value "/plugins/plugin-$actions/button-title" uint 3
    set_value "/plugins/plugin-$actions/custom-title" string '⏻'
    set_value "/plugins/plugin-$whisker/menu-width" int 480
    set_value "/plugins/plugin-$whisker/menu-height" int 520
    set_value "/plugins/plugin-$whisker/button-icon" string \
        "$HOME/.local/share/icons/hicolor/scalable/apps/void-experience-menu.svg"
    set_value "/plugins/plugin-$whisker/show-button-icon" bool true
    set_value "/plugins/plugin-$whisker/show-button-title" bool false

    network_template="$HOME/.local/share/void-experience/genmon-network.rc"
    if [ -f "$network_template" ]; then
        mkdir -p "$HOME/.config/xfce4/panel"
        sed "s|@HOME@|$HOME|g" "$network_template" \
            >"$HOME/.config/xfce4/panel/genmon-$network.rc"
    fi

    if [ "$monitor_index" -eq 0 ]; then
        tray=$((base + 9))
        xkb=$((base + 10))
        configure_common_plugin "$tray" systray
        configure_common_plugin "$xkb" xkb
        set_value "/plugins/plugin-$tray/icon-size" int 16
        set_value "/plugins/plugin-$tray/single-row" bool true
        set_value "/plugins/plugin-$tray/square-icons" bool true
        set_value "/plugins/plugin-$tray/symbolic-icons" bool true
        set_value "/plugins/plugin-$tray/hide-new-items" bool true
        set_value "/plugins/plugin-$xkb/display-type" uint 0
        set_value "/plugins/plugin-$xkb/display-name" uint 1
        set_value "/plugins/plugin-$xkb/display-scale" uint 78
        set_value "/plugins/plugin-$xkb/show-notifications" bool false
        write_int_array "/panels/panel-$panel_id/plugin-ids" \
            "$whisker" "$pager" "$tasklist" "$spacer" "$tray" "$xkb" \
            "$audio" "$network" "$clock" "$actions" "$edge"
    else
        write_int_array "/panels/panel-$panel_id/plugin-ids" \
            "$whisker" "$pager" "$tasklist" "$spacer" "$audio" \
            "$network" "$clock" "$actions" "$edge"
    fi

    panel_ids="$panel_ids $panel_id"
    monitor_index=$((monitor_index + 1))
done

# Replace the active XFCE panel list only after every new panel is configured.
# GNOME does not consume this xfconf channel.
# shellcheck disable=SC2086
write_int_array /panels $panel_ids
set_value /panels/dark-mode bool true

xfconf-query -c xfwm4 -p /general/workspace_count -s 4
xfconf-query -c xfwm4 -p /general/workspace_names -a \
    -t string -s 1 -t string -s 2 -t string -s 3 -t string -s 4

xfce4-panel --restart
echo "Created $monitor_index monitor-aware Void Experience panel(s)."
